// bibliography plugin — render the citation bibliography and inject it into
// the document after all citations have been resolved.
//
// Runs after enscribeCiteResolution (so citations.order is populated) and
// before hast conversion (the __bibliography internal node it produces is
// rendered by the cite handler).
//
// Placement strategy (article → article-back; book → book-back):
//   - If the author placed an explicit <bibliography> tag in the document, it
//     will be inside the back-matter region's content (bibliography is in
//     BACK_MATTER_TAGS / a book's back-matter). Find it there and replace it
//     with the __bibliography internal node.
//   - Otherwise: find/create the back-matter region (article-back or
//     book-back) and push __bibliography to its end (after the note-list,
//     which uses unshift).
//
// Empty case: if no citations were resolved (order is empty), remove any
// author-placed <bibliography> and do nothing else.
//
// The bibliography HTML is generated by citation-js with id="ref-KEY" injected
// into each entry's div via a string replace. This gives the hover-preview
// getCiteContent() something to look up with document.getElementById('ref-KEY').

import { makeTag, makeInternalMarker } from '../../core/tag.js';
import { ENSCRIBE_CITATIONS, ENSCRIBE_CONFIG, ENSCRIBE_MINIPAGE_SUBRUN } from '../../core/file-data-keys.js';
import { isEnscribeTag } from '../lib/ast-helpers.js';
import { isBookRegionTag } from '../lib/book-regions.js';
import { escapeHtmlAttr } from '../../core/escape-html.js';
import { findOrCreateBackMatter } from '../lib/back-matter.js'; // #264: shared home

// The bibliography heading override (#23) is emitted as a raw hast node
// (cite.js bibliographyHandler), so author-supplied text is HTML-escaped to avoid
// injecting markup. Uses the shared quote-escaping escaper (escapeHtmlAttr, #254) —
// the 4-entity superset, preserving this site's pre-consolidation `"`-escaping.

// ─── Deep-search helpers (same pattern as notes.js) ──────────────────────────

function findDeep(nodes, tagname) {
  for (const node of nodes) {
    if (isEnscribeTag(node, tagname)) return node;
    if (isEnscribeTag(node) && Array.isArray(node.content)) {
      const found = findDeep(node.content, tagname);
      if (found) return found;
    }
    if (node.children && Array.isArray(node.children)) {
      const found = findDeep(node.children, tagname);
      if (found) return found;
    }
  }
  return null;
}


// ─── Internal node factory ────────────────────────────────────────────────────

/**
 * Build a __bibliography internal node.
 * kwargs.html contains the full rendered bibliography HTML (no outer wrapper;
 * the handler provides the <bibliography> element).
 *
 * Phase 5 slice 5d (2026-05-28): also carry the structured CSL-JSON
 * entries in document-citation order so the JATS exporter can emit
 * `<element-citation>` with per-field structured data (vs. the HTML
 * side's formatted-string `bibBodyHtml`). The JATS path reads
 * `kwargs.cslEntries`; the HTML path ignores it.
 */
// #413 L7: the body of an empty-References placeholder — an AUTHORED <bibliography> that resolved no
// citations keeps its "References" heading and shows this visible note, rather than being silently
// spliced out. Intuitive (reads as a placeholder under the heading the author wrote); no new CSS.
const EMPTY_BIB_BODY = '<p><em>No citations resolved.</em></p>';

function makeBibliographyNode(headingHtml, bibBodyHtml, cslEntries, chapterScoped = false) {
  return makeInternalMarker('__bibliography', {
    kwargs: {
      headingHtml, // "References" heading HTML (may be overridden later)
      bibBodyHtml, // citation-js output with id= injected
      cslEntries,  // Phase 5 slice 5d: structured CSL-JSON entries (JATS path)
      // #190 split_bib: a per-chapter bibliography is HTML-only — the JATS exporter
      // emits a document-wide <ref-list> only (per-chapter JATS ref-lists are deferred),
      // so it skips a chapterScoped node. The HTML handler ignores this flag.
      ...(chapterScoped ? { chapterScoped: true } : {}),
    },
  });
}

// ─── Bibliography HTML generation ────────────────────────────────────────────

/**
 * Format the bibliography HTML for all cited entries and inject id="ref-KEY"
 * into each .csl-entry div for hover-preview lookup.
 *
 * citation-js output:
 *   <div class="csl-bib-body">
 *     <div data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 *
 * After injection:
 *   <div class="csl-bib-body">
 *     <div id="ref-KEY" data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 */
function formatBibliography(cite, style, entry) {
  const html = cite.format('bibliography', {
    template: style,
    format: 'html',
    lang: 'en-US',
    // #190 split_bib: an `entry` key-list filters the bibliography to just those
    // references (a per-chapter bib); omitted = the whole merged registry (document-wide).
    ...(entry ? { entry } : {}),
  });
  // Inject id="ref-KEY" alongside each data-csl-entry-id="KEY" attribute.
  // BibTeX keys are alphanumeric + hyphens/underscores — safe for id attributes.
  return html.replace(
    /data-csl-entry-id="([^"]+)"/g,
    (_, key) => `id="ref-${key}" data-csl-entry-id="${key}"`,
  );
}

// ─── Author-placement helpers ─────────────────────────────────────────────────

/**
 * Find the first author-placed <bibliography> tag node inside the
 * back-matter region (<article-back> for an article, <book-back> for a
 * book). Returns { backNode, index } or null.
 */
function findAuthorPlacedBibliography(treeChildren) {
  const article = findDeep(treeChildren, 'article');
  const root = article ?? findDeep(treeChildren, 'book');
  if (!root) return null;

  const backName = article ? 'article-back' : 'book-back';
  const back = findDeep(root.content ?? [], backName);
  if (!back || !Array.isArray(back.content)) return null;

  const idx = back.content.findIndex(n => isEnscribeTag(n, 'bibliography'));
  if (idx === -1) return null;

  return { backNode: back, index: idx };
}

// ─── Per-chapter (split_bib) helpers (#190) ────────────────────────────────────

// Top-level book-parts (chapters), in document order, across the book's regions —
// the unit a chapter-placed <bibliography> scopes to. Mirrors note-placement's
// findCollectionUnits('chapter'): OUTERMOST book-parts only (a nested part absorbs its
// children's citations, the same rule per-chapter notes use).
function findBookPartUnits(treeChildren) {
  const book = findDeep(treeChildren, 'book');
  if (!book) return [];
  const units = [];
  for (const region of book.content ?? []) {
    if (!isEnscribeTag(region)) continue;
    if (!isBookRegionTag(region.tagname)) continue;
    for (const child of region.content ?? []) {
      if (isEnscribeTag(child, 'book-part')) units.push(child);
    }
  }
  return units;
}

// Deep-find a <bibliography> ANYWHERE in a subtree, returning the array + index that
// holds it (so it can be replaced/removed in place). A chapter's <bibliography> nests
// under the chapter's section (the heading wraps the trailing content), so a shallow
// search misses it. Searches .content (enscribeTag) and .children (mdast).
function findBibWithParent(root) {
  for (const arr of [root.content, root.children]) {
    if (!Array.isArray(arr)) continue;
    const idx = arr.findIndex(n => isEnscribeTag(n, 'bibliography'));
    if (idx !== -1) return { parent: arr, index: idx };
    for (const child of arr) {
      if (child && typeof child === 'object') {
        const found = findBibWithParent(child);
        if (found) return found;
      }
    }
  }
  return null;
}

// Chapter-placed <bibliography> markers: a <bibliography> that survives INSIDE a
// book-part's subtree (the assembler marks a child's own bibliography `chapter-scoped`
// so book-structuring keeps it in the book-part instead of routing it to back-matter —
// see master-document.md §Citations). Distinct from the document-wide one in <book-back>.
// Returns one { unit, parent, index } per book-part holding a <bibliography>.
function findChapterPlacedBibliographies(treeChildren) {
  const out = [];
  for (const unit of findBookPartUnits(treeChildren)) {
    const at = findBibWithParent(unit);
    if (at) out.push({ unit, parent: at.parent, index: at.index });
  }
  return out;
}

// The cited keys, in first-cited order, that appear INSIDE this book-part's subtree —
// the split_bib entry set. After cite-resolution each <cite> is a __cite-marker
// (kwargs.keys = comma-joined keys) physically inside the chapter that cited it, so a
// subtree DFS recovers per-chapter ownership with NO change to the cite pipeline. Keys
// absent from the registry (a missing @key — its inline cite already shows the error)
// are dropped; a per-chapter bibliography lists only resolvable references.
function collectChapterCiteKeys(unit, cslById) {
  const ordered = [];
  const seen = new Set();
  const visit = (node) => {
    if (node == null) return;
    if (isEnscribeTag(node, '__cite-marker')) {
      for (const raw of String(node.kwargs?.keys ?? '').split(',')) {
        const key = raw.trim();
        if (key && cslById.has(key) && !seen.has(key)) { seen.add(key); ordered.push(key); }
      }
    }
    if (Array.isArray(node.content)) for (const c of node.content) visit(c);
    if (Array.isArray(node.children)) for (const c of node.children) visit(c);
  };
  visit(unit);
  return ordered;
}

// ─── Plugin ───────────────────────────────────────────────────────────────────

/**
 * Unified plugin. Renders the bibliography and injects it into the document.
 *
 * @returns {(tree: import('mdast').Root, file: import('vfile').VFile) => void}
 */
export function enscribeBibliography() {
  return (tree, file) => {
    const citations = file?.data?.[ENSCRIBE_CITATIONS];

    // #411: a minipage sub-run never renders a bibliography — one document, one
    // References. The seal seeds the DOCUMENT's citation index into the box (so
    // boxed cites resolve and join the shared `order`), which would otherwise
    // make this plugin auto-place a full document References inside every
    // citing box. Authored <bibliography> markers in a box are removed with a
    // warning (their home is the document); the box's cites are listed by the
    // DOCUMENT's References via the shared order (see index.js's deferred-phase
    // seeding comment — the contract lives there).
    if (file?.data?.[ENSCRIBE_MINIPAGE_SUBRUN]) {
      const boxAuthorPlaced = findAuthorPlacedBibliography(tree.children);
      const boxChapterPlaced = findChapterPlacedBibliographies(tree.children);
      if (boxAuthorPlaced) {
        boxAuthorPlaced.backNode.content.splice(boxAuthorPlaced.index, 1);
        file?.message?.('bibliography: a <bibliography> inside a minipage is removed — one document, one References (#411)');
      }
      for (const { parent, index } of boxChapterPlaced.reverse()) {
        parent.splice(index, 1);
        file?.message?.('bibliography: a <bibliography> inside a minipage is removed — one document, one References (#411)');
      }
      return;
    }

    const authorPlaced = findAuthorPlacedBibliography(tree.children);
    const chapterPlaced = findChapterPlacedBibliographies(tree.children);

    // #23: the bibliography heading text is a config override (the
    // `bibliography-heading` key); the default stays "References". headingHtml is
    // emitted raw, so the author-supplied text is HTML-escaped before the wrapper.
    const headingText =
      file?.data?.[ENSCRIBE_CONFIG]?.get('bibliography-heading') ?? 'References';
    const headingHtml = `<h2>${escapeHtmlAttr(headingText)}</h2>`;

    if (!citations || !citations.cite || citations.order.length === 0) {
      // #413 L7: an AUTHORED <bibliography> that resolves no citations is a "produces-nothing" placement
      // element → leave a visible empty-References placeholder + warn (BOTH channels), never a silent
      // splice-out. Gated on the marker being AUTHORED: a document with no <bibliography> written (no
      // authorPlaced, empty chapterPlaced) still renders nothing — the placeholder is only where the
      // author explicitly asked for a bibliography. (1-for-1 splice-replace; the arrays don't shift.)
      if (authorPlaced) {
        authorPlaced.backNode.content.splice(authorPlaced.index, 1, makeBibliographyNode(headingHtml, EMPTY_BIB_BODY, []));
        file?.message?.('bibliography: an authored <bibliography> resolved no citations — rendering an empty-References placeholder');
      }
      for (const { parent, index } of chapterPlaced) {
        parent.splice(index, 1, makeBibliographyNode(headingHtml, EMPTY_BIB_BODY, [], true));
        file?.message?.('bibliography: a chapter <bibliography> resolved no citations — rendering an empty-References placeholder');
      }
      return;
    }

    const { cite, style, order } = citations;
    const cslById = new Map((cite?.data ?? []).map(e => [e.id, e]));

    // #190 split_bib: a <bibliography> authored inside a chapter lists ONLY that
    // chapter's cited references (drawn from the one merged registry, so a key cited in
    // two chapters appears in each — see master-document.md §Citations). Replace each in
    // place; a chapter that cites nothing drops its (empty) marker, mirroring the
    // document-wide empty case. (Each {parent,index} is an independent array, no shift.)
    for (const { unit, parent, index } of chapterPlaced) {
      const chapterKeys = collectChapterCiteKeys(unit, cslById);
      if (chapterKeys.length === 0) {
        // #413 L7: an authored chapter <bibliography> whose chapter cites nothing — empty-References
        // placeholder + warn (both channels), mirroring the document-wide empty case above.
        parent.splice(index, 1, makeBibliographyNode(headingHtml, EMPTY_BIB_BODY, [], true));
        file?.message?.('bibliography: a chapter <bibliography> resolved no citations — rendering an empty-References placeholder');
        continue;
      }
      const chapterBody = formatBibliography(cite, style, chapterKeys);
      const chapterEntries = chapterKeys.map(key => cslById.get(key)).filter(Boolean);
      parent.splice(index, 1, makeBibliographyNode(headingHtml, chapterBody, chapterEntries, true));
    }

    // Document-wide bibliography — lists everything in citation order (Phase 5 slice 5d:
    // cslEntries are the structured CSL-JSON the JATS exporter reads). Unchanged.
    const bibBodyHtml = formatBibliography(cite, style);
    const cslEntries = order.map(key => cslById.get(key)).filter(Boolean);
    const bibNode = makeBibliographyNode(headingHtml, bibBodyHtml, cslEntries);

    if (authorPlaced) {
      // An explicit back-matter <bibliography> → the document-wide bib, in place. It
      // coexists with any per-chapter bibs (book-level lists everything).
      authorPlaced.backNode.content.splice(authorPlaced.index, 1, bibNode);
    } else if (chapterPlaced.length === 0) {
      // Default (no <bibliography> markers at all): auto-place one document-wide bib at
      // back-matter (after notes, which used unshift). When the author opted into
      // per-chapter bibs, split_bib REPLACES the auto-placed document-wide one — a
      // book-level bib is then opt-in via an explicit back-matter <bibliography>.
      const back = findOrCreateBackMatter(tree.children);
      if (back) back.content.push(bibNode);
    }
  };
}
