// enscribe docs-site — authoring coverage gallery generator.
//
// Builds the "Gallery" page: the project's *completeness* surface — every
// authoring construct a user can write, shown as authored source beside its
// live-rendered output. It is the *human* verification surface (a person looks
// at it to confirm the language works), complementing the fixture corpus (the
// machine regression corpus).
//
// Two sources feed it:
//   • Every Layer 1 vocabulary element — generated by walking
//     `@enscribejs/layer1-vocabulary`'s `VOCABULARY` data and rendering each
//     element's `shorthand_examples` through the *same* pipeline the rest of the
//     docs site uses (passed in as `render`).
//   • A curated supplement of NON-vocabulary constructs (Layer-2 authoring with
//     no vocab entry of its own — the `<list>` family) from `gallery-non-vocab.js`
//     (#143). The gallery owns completeness, so a construct with no vocab element
//     is not faked into one (that would break the vocab/Layer-1 boundary) — it is
//     curated here instead.
//
// For the vocab-driven groups, completeness is mechanical:
//
//   • An element grouped by its `category` frontmatter field.
//   • An authorable element with no examples renders a loud GAP marker — never
//     silently absent.
//   • An element marked `authoring: generated` (a structural/region wrapper the
//     pipeline produces, not authored directly) with no examples renders a
//     muted "generated — not authored directly" note instead of a GAP.
//   • An element whose `category` is not in the known taxonomy lands in a loud
//     "⚠ Uncategorized" group, so a new/mis-tagged element can't hide.
//
// The coverage *contract* is "examples are the contract": the gallery renders
// the examples the vocab entries carry. Broadening it to an exhaustive
// forms × options matrix (encoding form-support and per-value coverage in the
// vocab schema) is deferred — see the v0.3.0 gallery slice report and #5.

import { VOCABULARY } from '@enscribejs/layer1-vocabulary';
import { NON_VOCAB_CONSTRUCTS } from './gallery-non-vocab.js';

// Category display order + human labels. The keys are the `category` field
// values written into each element's frontmatter (see
// packages/layer1-vocabulary/SPEC.md "Element categories"). Any element whose
// category is absent from this list is surfaced loudly (see below), so adding a
// new category here is the single place the gallery's grouping is configured.
const CATEGORY_ORDER = [
  ['document-containers', 'Document containers'],
  ['structural-regions', 'Structural regions'],
  ['sections', 'Sections'],
  ['block-prose', 'Block prose'],
  ['frameables', 'Frameables'],
  ['math', 'Math'],
  ['code', 'Code'],
  ['inline-formatting', 'Inline formatting'],
  ['citations-and-references', 'Citations & references'],
  ['structured-data-containers', 'Structured-data containers'],
  ['metadata', 'Document metadata'],
  ['theorem-family', 'Theorem family'],
];

const UNCATEGORIZED = '__uncategorized__';

const escapeHtml = (s) => String(s)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

// The pipeline prepends injected asset tags (CDN <link>s for fonts/KaTeX,
// <script>s for live-link DSLs) to every rendered fragment. Rendering each
// example separately would scatter hundreds of duplicates through the body, so
// peel the leading run of asset tags off the front of a fragment, returning the
// tags (to dedupe once into the page <head>) and the remaining content. Asset
// tags are always injected ahead of the `<article>` content, so a leading-only
// match is sufficient and never touches the rendered output itself.
function splitAssets(fragment) {
  const assets = [];
  let rest = fragment;
  const leading = /^\s*(<link\b[^>]*>|<script\b[^>]*>[\s\S]*?<\/script>|<style\b[^>]*>[\s\S]*?<\/style>)/i;
  let m;
  while ((m = rest.match(leading))) {
    assets.push(m[1].trim());
    rest = rest.slice(m[0].length);
  }
  return { assets, content: rest.trim() };
}

// One rendered example: the escaped source in a <pre>, the live output beside
// it, and the example's authoring note (if any). Always-renders: a throw from
// the pipeline becomes an inline error marker, never a blank entry.
function renderExample(ex, render, assetSet) {
  const src = ex.source ?? '';
  let outputHtml;
  try {
    const { assets, content } = splitAssets(render(src));
    for (const a of assets) assetSet.add(a);
    outputHtml = content || '<span class="gallery-empty">(no output)</span>';
  } catch (err) {
    outputHtml = `<div class="gallery-render-error">render error: ${escapeHtml(err.message)}</div>`;
  }
  const note = ex.notes
    ? `\n        <p class="gallery-note">${escapeHtml(String(ex.notes).replace(/\s+/g, ' ').trim())}</p>`
    : '';
  return (
    '      <div class="gallery-example">\n' +
    `        <pre class="gallery-source"><code>${escapeHtml(src)}</code></pre>\n` +
    `        <div class="gallery-render">${outputHtml}</div>${note}\n` +
    '      </div>'
  );
}

// One element block: heading, authoring-shorthand note, then either its
// examples, a GAP marker (authorable but no example), or a "generated" note.
function renderElement(spec, render, assetSet) {
  const name = spec.html_output?.element ?? '(unknown)';
  const examples = Array.isArray(spec.shorthand_examples) ? spec.shorthand_examples : [];
  const shorthands = (Array.isArray(spec.shorthand_expansions) ? spec.shorthand_expansions : [])
    .map((e) => e.shorthand)
    .filter(Boolean);

  const parts = [];
  parts.push(`    <section class="gallery-element" id="el-${escapeHtml(name)}">`);
  parts.push(`      <h3><code>&lt;${escapeHtml(name)}&gt;</code></h3>`);
  if (shorthands.length) {
    const list = shorthands.map((s) => `<code>&lt;${escapeHtml(s)}&gt;</code>`).join(', ');
    parts.push(`      <p class="gallery-aliases">Authoring shorthand: ${list}</p>`);
  }

  if (spec['requires-context']) {
    // #132 (Option A — annotate, don't inject context): some examples are
    // context-dependent (book-part shorthands need a book; <cite> needs a loaded
    // bibliography) and degrade to a misleading "unknown tag" render when the
    // gallery renders them in isolation. Show a short note instead of that render
    // — a third state alongside the GAP marker and the `authoring: generated`
    // note, reusing the same muted note style.
    const ctx = spec['requires-context'];
    const note = ctx === 'book'
      ? 'Renders only within a book.'
      : ctx === 'bibliography'
        ? 'Resolves against a loaded bibliography.'
        : `Requires ${escapeHtml(ctx)} context.`;
    parts.push(`      <p class="gallery-generated">${note}</p>`);
  } else if (examples.length) {
    for (const ex of examples) parts.push(renderExample(ex, render, assetSet));
  } else if (spec.authoring === 'generated') {
    parts.push(
      '      <p class="gallery-generated">Generated by the pipeline (a structural ' +
        'region/title wrapper) — not authored directly, so it carries no example.</p>',
    );
  } else {
    parts.push(
      `      <div class="gallery-gap">⚠ no example: <code>&lt;${escapeHtml(name)}&gt;</code> ` +
        'has no <code>shorthand_examples</code> in its vocab entry.</div>',
    );
  }
  parts.push('    </section>');
  return parts.join('\n');
}

// One non-vocabulary construct block (#143): a Layer-2 authoring construct with
// no vocab entry of its own (e.g. `<list>`, which lowers to `<ul>`/`<ol>`/`<li>`).
// Mirrors renderElement's shape — heading, a note, and example cells via the same
// renderExample — so it reads as a gallery element like any other.
function renderNonVocabConstruct(construct, render, assetSet) {
  const name = construct.element ?? '(unknown)';
  const parts = [];
  parts.push(`    <section class="gallery-element" id="el-${escapeHtml(name)}">`);
  parts.push(`      <h3><code>&lt;${escapeHtml(name)}&gt;</code></h3>`);
  if (construct.note) {
    parts.push(`      <p class="gallery-aliases">${escapeHtml(construct.note)}</p>`);
  }
  const examples = Array.isArray(construct.examples) ? construct.examples : [];
  for (const ex of examples) parts.push(renderExample(ex, render, assetSet));
  parts.push('    </section>');
  return parts.join('\n');
}

/**
 * Build the gallery page body and its deduped asset-head tags.
 *
 * @param {{ render: (src: string) => string }} opts - `render` turns an
 *   enscribe source string into an HTML fragment (the site's renderAcm).
 * @returns {{ body: string, headExtra: string }}
 */
export function buildGallery({ render }) {
  // Walk VOCABULARY, deduping shorthand aliases (which share their target's
  // spec object by reference) so each element file appears exactly once.
  const seen = new Set();
  const byCategory = new Map();
  for (const spec of Object.values(VOCABULARY)) {
    if (seen.has(spec)) continue;
    seen.add(spec);
    const cat = spec.category || UNCATEGORIZED;
    if (!byCategory.has(cat)) byCategory.set(cat, []);
    byCategory.get(cat).push(spec);
  }

  // Known categories in display order, then any unexpected categories last
  // (loudly), so a mis-tagged element surfaces rather than vanishing.
  const order = [...CATEGORY_ORDER];
  for (const cat of byCategory.keys()) {
    if (!order.some(([k]) => k === cat)) order.push([cat, `⚠ Uncategorized (${cat})`]);
  }

  const assetSet = new Set();
  const toc = [];
  const sections = [];

  for (const [cat, label] of order) {
    const specs = byCategory.get(cat);
    if (!specs || specs.length === 0) continue;
    specs.sort((a, b) => (a.html_output?.element || '').localeCompare(b.html_output?.element || ''));
    const catId = `cat-${cat}`;
    toc.push(`<li><a href="#${catId}">${escapeHtml(label)}</a></li>`);
    const elementBlocks = specs.map((s) => renderElement(s, render, assetSet)).join('\n');
    sections.push(
      `  <section class="gallery-category" id="${catId}">\n` +
        `    <h2>${escapeHtml(label)}</h2>\n` +
        `${elementBlocks}\n` +
        '  </section>',
    );
  }

  // #143: the curated non-vocabulary constructs (Layer-2 authoring with no vocab
  // entry — the `<list>` family). The gallery is the completeness surface, so
  // these render alongside the vocab-driven groups, in the same cell format, in a
  // final category rather than scattered into the vocab taxonomy.
  if (NON_VOCAB_CONSTRUCTS.length) {
    const catId = 'cat-non-vocab';
    toc.push(`<li><a href="#${catId}">Non-vocabulary constructs</a></li>`);
    const blocks = NON_VOCAB_CONSTRUCTS
      .map((c) => renderNonVocabConstruct(c, render, assetSet))
      .join('\n');
    sections.push(
      `  <section class="gallery-category" id="${catId}">\n` +
        '    <h2>Non-vocabulary constructs</h2>\n' +
        `${blocks}\n` +
        '  </section>',
    );
  }

  const intro =
    '  <h1>Vocabulary coverage gallery</h1>\n' +
    '  <p class="gallery-intro">Every authoring construct a user can write, as a look-it-up ' +
    'reference: each Layer 1 element generated from the ' +
    '<a href="https://github.com/enscribejs/enscribe/tree/main/packages/layer1-vocabulary/elements">' +
    'vocabulary entries</a>, plus a curated supplement of Layer-2 constructs that have no vocab ' +
    'entry of their own (the <code>&lt;list&gt;</code> family) — the authored source beside its ' +
    'live-rendered output, grouped by category. This is the human verification surface and the ' +
    'completeness surface for the authoring language; the fixture corpus is the machine regression ' +
    'corpus. Because the vocab groups are generated from the vocab data, a missing example shows as ' +
    'a loud <span class="gallery-gap-inline">GAP</span> marker rather than silently absent.</p>';

  // #135: the category nav is the floating side-ToC the doc pages use — reuse the
  // `.enscribe-layout--toc` grid + `.enscribe-toc` sidebar chrome (styled in
  // default.css + site.css), not the old inline top `.gallery-toc` bar.
  const categoryNav =
    '    <nav class="enscribe-toc" aria-label="Categories">\n' +
    '      <details class="enscribe-toc-details" open>\n' +
    '        <summary class="enscribe-toc-summary">Categories</summary>\n' +
    `        <ul>${toc.join('')}</ul>\n` +
    '      </details>\n' +
    '    </nav>';

  const body =
    '<main class="article gallery">\n' +
    '  <div class="enscribe-layout enscribe-layout--toc">\n' +
    `${categoryNav}\n` +
    '    <div class="enscribe-body">\n' +
    `${intro}\n` +
    `${sections.join('\n')}\n` +
    '    </div>\n' +
    '  </div>\n' +
    '    </main>\n' +
    '    <footer class="site-footer">\n' +
    '      Generated from the <a href="https://github.com/enscribejs/enscribe/tree/main/packages/layer1-vocabulary/elements">Layer 1 vocabulary entries</a> by <code>docs-site/gen-gallery.js</code>.\n' +
    '    </footer>';

  return { body, headExtra: [...assetSet].join('\n    ') };
}
