// bibliography plugin — render the citation bibliography and inject it into
// the document after all citations have been resolved.
//
// Runs after enscribeCiteResolution (so citations.order is populated) and
// before hast conversion (the __bibliography internal node it produces is
// rendered by the cite handler).
//
// Placement strategy (article → article-back; book → book-back):
//   - If the author placed an explicit <bibliography> tag in the document, it
//     will be inside the back-matter region's content (bibliography is in
//     BACK_MATTER_TAGS / a book's back-matter). Find it there and replace it
//     with the __bibliography internal node.
//   - Otherwise: find/create the back-matter region (article-back or
//     book-back) and push __bibliography to its end (after the note-list,
//     which uses unshift).
//
// Empty case: if no citations were resolved (order is empty), remove any
// author-placed <bibliography> and do nothing else.
//
// The bibliography HTML is generated by citation-js with id="ref-KEY" injected
// into each entry's div via a string replace. This gives the hover-preview
// getCiteContent() something to look up with document.getElementById('ref-KEY').

import { makeTag, makeInternalMarker } from '@enscribejs/core/tag';
import { ENSCRIBE_CITATIONS } from '@enscribejs/core/file-data-keys';
import { isEnscribeTag } from '../lib/ast-helpers.js';

// ─── Deep-search helpers (same pattern as notes.js) ──────────────────────────

function findDeep(nodes, tagname) {
  for (const node of nodes) {
    if (isEnscribeTag(node, tagname)) return node;
    if (isEnscribeTag(node) && Array.isArray(node.content)) {
      const found = findDeep(node.content, tagname);
      if (found) return found;
    }
    if (node.children && Array.isArray(node.children)) {
      const found = findDeep(node.children, tagname);
      if (found) return found;
    }
  }
  return null;
}

/**
 * Find (or create) the back-matter region that holds the bibliography:
 * <article-back> for an article, <book-back> for a book. Returns null if
 * the tree has neither root (nothing to attach to).
 *
 * Book case (Phase 6, 2026-05-29): a book's bibliography is a single
 * document-wide <ref-list> placed at the end of <book-back>, mirroring the
 * article path. Per-chapter bibliographies (scoped like note-scope=chapter)
 * are a deferred post-alpha option — see BACKLOG. book-structuring creates
 * <book-back> only when there is back-matter (appendix/glossary); if none
 * exists we create one and append it to the <book>.
 */
function findOrCreateBackMatter(treeChildren) {
  const article = findDeep(treeChildren, 'article');
  if (article) {
    let back = findDeep(article.content ?? [], 'article-back');
    if (!back) {
      back = makeTag('article-back');
      article.content.push(back);
    }
    return back;
  }

  const book = findDeep(treeChildren, 'book');
  if (book) {
    let back = findDeep(book.content ?? [], 'book-back');
    if (!back) {
      back = makeTag('book-back');
      book.content = book.content ?? [];
      book.content.push(back);
    }
    return back;
  }

  return null;
}

// ─── Internal node factory ────────────────────────────────────────────────────

/**
 * Build a __bibliography internal node.
 * kwargs.html contains the full rendered bibliography HTML (no outer wrapper;
 * the handler provides the <bibliography> element).
 *
 * Phase 5 slice 5d (2026-05-28): also carry the structured CSL-JSON
 * entries in document-citation order so the JATS exporter can emit
 * `<element-citation>` with per-field structured data (vs. the HTML
 * side's formatted-string `bibBodyHtml`). The JATS path reads
 * `kwargs.cslEntries`; the HTML path ignores it.
 */
function makeBibliographyNode(headingHtml, bibBodyHtml, cslEntries) {
  return makeInternalMarker('__bibliography', {
    kwargs: {
      headingHtml, // "References" heading HTML (may be overridden later)
      bibBodyHtml, // citation-js output with id= injected
      cslEntries,  // Phase 5 slice 5d: structured CSL-JSON entries (JATS path)
    },
  });
}

// ─── Bibliography HTML generation ────────────────────────────────────────────

/**
 * Format the bibliography HTML for all cited entries and inject id="ref-KEY"
 * into each .csl-entry div for hover-preview lookup.
 *
 * citation-js output:
 *   <div class="csl-bib-body">
 *     <div data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 *
 * After injection:
 *   <div class="csl-bib-body">
 *     <div id="ref-KEY" data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 */
function formatBibliography(cite, style) {
  const html = cite.format('bibliography', {
    template: style,
    format: 'html',
    lang: 'en-US',
  });
  // Inject id="ref-KEY" alongside each data-csl-entry-id="KEY" attribute.
  // BibTeX keys are alphanumeric + hyphens/underscores — safe for id attributes.
  return html.replace(
    /data-csl-entry-id="([^"]+)"/g,
    (_, key) => `id="ref-${key}" data-csl-entry-id="${key}"`,
  );
}

// ─── Author-placement helpers ─────────────────────────────────────────────────

/**
 * Find the first author-placed <bibliography> tag node inside the
 * back-matter region (<article-back> for an article, <book-back> for a
 * book). Returns { backNode, index } or null.
 */
function findAuthorPlacedBibliography(treeChildren) {
  const article = findDeep(treeChildren, 'article');
  const root = article ?? findDeep(treeChildren, 'book');
  if (!root) return null;

  const backName = article ? 'article-back' : 'book-back';
  const back = findDeep(root.content ?? [], backName);
  if (!back || !Array.isArray(back.content)) return null;

  const idx = back.content.findIndex(n => isEnscribeTag(n, 'bibliography'));
  if (idx === -1) return null;

  return { backNode: back, index: idx };
}

// ─── Plugin ───────────────────────────────────────────────────────────────────

/**
 * Unified plugin. Renders the bibliography and injects it into the document.
 *
 * @returns {(tree: import('mdast').Root, file: import('vfile').VFile) => void}
 */
export function enscribeBibliography() {
  return (tree, file) => {
    const citations = file?.data?.[ENSCRIBE_CITATIONS];

    const authorPlaced = findAuthorPlacedBibliography(tree.children);

    if (!citations || !citations.cite || citations.order.length === 0) {
      // No citations resolved → remove any author-placed <bibliography>.
      if (authorPlaced) {
        authorPlaced.backNode.content.splice(authorPlaced.index, 1);
      }
      return;
    }

    const { cite, style, order } = citations;

    // Render HTML (the existing path; for HTML output).
    const bibBodyHtml = formatBibliography(cite, style);
    // Phase 5 slice 5d: also gather the structured CSL-JSON entries in
    // document-citation order (the same order the HTML bibliography
    // renders in). The JATS exporter uses this to emit
    // `<element-citation>` with per-field structured data.
    const cslById = new Map((cite?.data ?? []).map(e => [e.id, e]));
    const cslEntries = order.map(key => cslById.get(key)).filter(Boolean);
    const bibNode = makeBibliographyNode('<h2>References</h2>', bibBodyHtml, cslEntries);

    if (authorPlaced) {
      // Replace the author-placed <bibliography> node in-place.
      authorPlaced.backNode.content.splice(authorPlaced.index, 1, bibNode);
    } else {
      // Auto-place: append to the back-matter region (article-back or
      // book-back) after notes, which used unshift.
      const back = findOrCreateBackMatter(tree.children);
      if (back) {
        back.content.push(bibNode);
      }
    }
  };
}
