// bibliography plugin — render the citation bibliography and inject it into
// the document after all citations have been resolved.
//
// Runs after acadamarkCiteResolution (so citations.order is populated) and
// before hast conversion (the __bibliography internal node it produces is
// rendered by the cite handler).
//
// Placement strategy:
//   - If the author placed an explicit <bibliography> tag in the document, it
//     will be inside article-back.content (since bibliography is in BACK_MATTER_TAGS).
//     Find it there and replace it with the __bibliography internal node.
//   - Otherwise: find/create article-back and push __bibliography to its end
//     (after the note-list, which uses unshift).
//
// Empty case: if no citations were resolved (order is empty), remove any
// author-placed <bibliography> and do nothing else.
//
// The bibliography HTML is generated by citation-js with id="ref-KEY" injected
// into each entry's div via a string replace. This gives the hover-preview
// getCiteContent() something to look up with document.getElementById('ref-KEY').

import { makeTag, makeInternalMarker } from 'acadamark-core/tag';
import { ACADAMARK_CITATIONS } from 'acadamark-core/file-data-keys';
import { isAcadamarkTag } from '../lib/ast-helpers.js';

// ─── Deep-search helpers (same pattern as notes.js) ──────────────────────────

function findDeep(nodes, tagname) {
  for (const node of nodes) {
    if (isAcadamarkTag(node, tagname)) return node;
    if (isAcadamarkTag(node) && Array.isArray(node.content)) {
      const found = findDeep(node.content, tagname);
      if (found) return found;
    }
    if (node.children && Array.isArray(node.children)) {
      const found = findDeep(node.children, tagname);
      if (found) return found;
    }
  }
  return null;
}

function findOrCreateArticleBack(treeChildren) {
  const article = findDeep(treeChildren, 'article');
  if (!article) return null;

  let back = findDeep(article.content ?? [], 'article-back');
  if (!back) {
    back = makeTag('article-back');
    article.content.push(back);
  }
  return back;
}

// ─── Internal node factory ────────────────────────────────────────────────────

/**
 * Build a __bibliography internal node.
 * kwargs.html contains the full rendered bibliography HTML (no outer wrapper;
 * the handler provides the <bibliography> element).
 *
 * Phase 5 slice 5d (2026-05-28): also carry the structured CSL-JSON
 * entries in document-citation order so the JATS exporter can emit
 * `<element-citation>` with per-field structured data (vs. the HTML
 * side's formatted-string `bibBodyHtml`). The JATS path reads
 * `kwargs.cslEntries`; the HTML path ignores it.
 */
function makeBibliographyNode(headingHtml, bibBodyHtml, cslEntries) {
  return makeInternalMarker('__bibliography', {
    kwargs: {
      headingHtml, // "References" heading HTML (may be overridden later)
      bibBodyHtml, // citation-js output with id= injected
      cslEntries,  // Phase 5 slice 5d: structured CSL-JSON entries (JATS path)
    },
  });
}

// ─── Bibliography HTML generation ────────────────────────────────────────────

/**
 * Format the bibliography HTML for all cited entries and inject id="ref-KEY"
 * into each .csl-entry div for hover-preview lookup.
 *
 * citation-js output:
 *   <div class="csl-bib-body">
 *     <div data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 *
 * After injection:
 *   <div class="csl-bib-body">
 *     <div id="ref-KEY" data-csl-entry-id="KEY" class="csl-entry">...</div>
 *   </div>
 */
function formatBibliography(cite, style) {
  const html = cite.format('bibliography', {
    template: style,
    format: 'html',
    lang: 'en-US',
  });
  // Inject id="ref-KEY" alongside each data-csl-entry-id="KEY" attribute.
  // BibTeX keys are alphanumeric + hyphens/underscores — safe for id attributes.
  return html.replace(
    /data-csl-entry-id="([^"]+)"/g,
    (_, key) => `id="ref-${key}" data-csl-entry-id="${key}"`,
  );
}

// ─── Author-placement helpers ─────────────────────────────────────────────────

/**
 * Find the first <bibliography> tag node inside article-back.
 * Returns { backNode, index } or null.
 */
function findAuthorPlacedBibliography(treeChildren) {
  const article = findDeep(treeChildren, 'article');
  if (!article) return null;

  const back = findDeep(article.content ?? [], 'article-back');
  if (!back || !Array.isArray(back.content)) return null;

  const idx = back.content.findIndex(n => isAcadamarkTag(n, 'bibliography'));
  if (idx === -1) return null;

  return { backNode: back, index: idx };
}

// ─── Plugin ───────────────────────────────────────────────────────────────────

/**
 * Unified plugin. Renders the bibliography and injects it into the document.
 *
 * @returns {(tree: import('mdast').Root, file: import('vfile').VFile) => void}
 */
export function acadamarkBibliography() {
  return (tree, file) => {
    const citations = file?.data?.[ACADAMARK_CITATIONS];

    const authorPlaced = findAuthorPlacedBibliography(tree.children);

    if (!citations || !citations.cite || citations.order.length === 0) {
      // No citations resolved → remove any author-placed <bibliography>.
      if (authorPlaced) {
        authorPlaced.backNode.content.splice(authorPlaced.index, 1);
      }
      return;
    }

    const { cite, style, order } = citations;

    // Render HTML (the existing path; for HTML output).
    const bibBodyHtml = formatBibliography(cite, style);
    // Phase 5 slice 5d: also gather the structured CSL-JSON entries in
    // document-citation order (the same order the HTML bibliography
    // renders in). The JATS exporter uses this to emit
    // `<element-citation>` with per-field structured data.
    const cslById = new Map((cite?.data ?? []).map(e => [e.id, e]));
    const cslEntries = order.map(key => cslById.get(key)).filter(Boolean);
    const bibNode = makeBibliographyNode('<h2>References</h2>', bibBodyHtml, cslEntries);

    if (authorPlaced) {
      // Replace the author-placed <bibliography> node in-place.
      authorPlaced.backNode.content.splice(authorPlaced.index, 1, bibNode);
    } else {
      // Auto-place: append to article-back (after notes, which used unshift).
      const back = findOrCreateArticleBack(tree.children);
      if (back) {
        back.content.push(bibNode);
      }
    }
  };
}
