import assert from 'node:assert/strict';
import { loadVocabulary, parseFrontmatter } from '../../src/schema/load-vocabulary.js';

export function run() {
  // parseFrontmatter on a simple synthetic source.
  const sample = `---\nsemantic_role: foo\nhtml_output:\n  element: foo\n---\nbody text\n`;
  const parsed = parseFrontmatter(sample);
  assert.equal(parsed.semantic_role, 'foo');
  assert.equal(parsed.html_output.element, 'foo');
  console.log('PASS: parseFrontmatter extracts YAML');

  // No frontmatter -> null.
  assert.equal(parseFrontmatter('no frontmatter here'), null);
  console.log('PASS: parseFrontmatter returns null on missing frontmatter');

  // Real vocabulary load.
  const v = loadVocabulary();
  assert.equal(v.size, 67, `expected 67 entries (66 + 'quote' shorthand alias), got ${v.size}`);
  console.log(`PASS: loadVocabulary returned ${v.size} entries`);

  // Spot-check the in-scope structural elements.
  const required = [
    'article', 'section', 'sub-section', 'sub-sub-section',
    'p', 'aside', 'blockquote', 'hr', 'figure',
    'ul', 'ol', 'li',
    'em', 'strong', 'code',
    'meta',
    'inline-math', 'display-math',
    'code-block', 'inline-code',
    // AUD-12: shorthand alias
    'quote',
  ];
  for (const r of required) {
    assert.ok(v.has(r), `missing in-scope vocabulary entry: ${r}`);
  }
  console.log('PASS: all 21 in-scope elements present (including quote alias)');

  // <quote> is an alias pointing at the same spec object as <blockquote> (AUD-12).
  assert.ok(v.get('quote') === v.get('blockquote'), 'quote alias must point at blockquote spec');
  console.log('PASS: quote shorthand alias points at blockquote spec');

  // Spot-check structural-plugin output entries — the six region wrappers
  // generated by acadamarkArticleStructuring / acadamarkBookStructuring,
  // plus title/subtitle elements promoted from <meta>.
  const generated = [
    'article-front', 'article-body', 'article-back',
    'book-front', 'book-body', 'book-back',
    'article-title', 'article-subtitle',
    'book-title', 'book-subtitle',
    'book-part-title', 'book-part-subtitle',
    'section-title', 'section-subtitle',
    'sub-section-title', 'sub-section-subtitle',
    'sub-sub-section-title', 'sub-sub-section-subtitle',
  ];
  for (const g of generated) {
    assert.ok(v.has(g), `missing auto-generated entry: ${g}`);
  }
  console.log('PASS: auto-generated wrapper + title/subtitle entries present');

  // book-part-meta was removed (book-parts use <meta> directly).
  assert.equal(v.has('book-part-meta'), false, 'book-part-meta should not exist');
  console.log('PASS: book-part-meta absent from vocabulary');

  // Field shape spot-check on <p>.
  const p = v.get('p');
  assert.equal(p.html_output.element, 'p');
  assert.equal(p.interpreter_strategy, 'schema');
  console.log('PASS: <p> entry has expected html_output.element and interpreter_strategy');

  // <figure> is the handler-strategy case (figure.md YAML fix verified).
  const fig = v.get('figure');
  assert.equal(fig.interpreter_strategy, 'handler');
  assert.ok(fig.handler_module, 'expected handler_module on figure entry');
  console.log('PASS: <figure> uses handler strategy with handler_module set');

  // <meta> declares a type kwarg driving the meta-driven document type model.
  const meta = v.get('meta');
  assert.ok(meta.acadamark_attributes?.kwargs?.type, 'meta must declare type kwarg');
  const typeValues = meta.acadamark_attributes.kwargs.type.values ?? [];
  for (const t of ['article', 'book', 'book-part']) {
    assert.ok(typeValues.includes(t), `meta type values must include ${t}, got ${JSON.stringify(typeValues)}`);
  }
  assert.equal(typeValues.includes('report'), false, 'report should not be in meta type values (deferred)');
  console.log('PASS: <meta> declares type kwarg with article/book/book-part values (report excluded)');

  // <article> still declares title_extraction (the explicit-form path).
  const art = v.get('article');
  assert.equal(art.title_extraction, true);
  console.log('PASS: <article> declares title_extraction: true');
}
